apiVersion: v1
kind: Secret
metadata:
  name: media-downloader-secret
  namespace: media-downloader
  labels:
    app: media-downloader
type: Opaque
stringData:
  secret-key: "${SECRET_KEY}"
  tmdb-api-key: "${TMDB_API_KEY}"
  prowlarr-api-key: "${PROWLARR_API_KEY}"
  qbittorrent-username: "${QBITTORRENT_USERNAME}"
  qbittorrent-password: "${QBITTORRENT_PASSWORD}"
