apiVersion: v1
kind: Service
metadata:
  name: media-downloader-service
  namespace: media-downloader
  labels:
    app: media-downloader
spec:
  type: NodePort
  selector:
    app: media-downloader
  ports:
    - port: 80
      targetPort: 8095
      nodePort: 30001
